# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datumctl < Formula
  desc "A network cloud, built on open source."
  homepage "https://www.datum.net/"
  version "0.15.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.15.1/datumctl_Darwin_x86_64.tar.gz"
      sha256 "1a1dce176eaeb6e7294fec7bead8d3419fa5f4110a461711d69bbd7860fa9bc5"

      define_method(:install) do
        bin.install "datumctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.15.1/datumctl_Darwin_arm64.tar.gz"
      sha256 "5be8c931453c81fe791130d1a884f23382602d28224540801b59dee5a8bf151e"

      define_method(:install) do
        bin.install "datumctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.15.1/datumctl_Linux_x86_64.tar.gz"
      sha256 "9a8191992e83615dd9e31f9654044b837a5ec8ea77d8acf332ea588801d8b813"
      define_method(:install) do
        bin.install "datumctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.15.1/datumctl_Linux_arm64.tar.gz"
      sha256 "db6a0aa50f309f235f8dd355ee47d79e0f92d25d6a75ed17928979972cc22e27"
      define_method(:install) do
        bin.install "datumctl"
      end
    end
  end
end
