# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datumctl < Formula
  desc "A network cloud, built on open source."
  homepage "https://www.datum.net/"
  version "0.0.4"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.0.4/datumctl_Darwin_x86_64.tar.gz"
      sha256 "6c1cd38f493107c215fcca75f19dda9a458c40e7a4b04ae75ddeb967e0448d4c"

      def install
        bin.install "datumctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.0.4/datumctl_Darwin_arm64.tar.gz"
      sha256 "647ce867d9d1e28c87a209a49f89795f19d784812ea6f0bd78fb5fa4c351504e"

      def install
        bin.install "datumctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/datum-cloud/datumctl/releases/download/v0.0.4/datumctl_Linux_x86_64.tar.gz"
        sha256 "8979751c532b83066e2f58d7d3e8fd1014068054a0ce13a00da356489380e955"

        def install
          bin.install "datumctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/datum-cloud/datumctl/releases/download/v0.0.4/datumctl_Linux_arm64.tar.gz"
        sha256 "f5bd921c4f7fad4dac8daeafc6165f53395ea846e851be21b27edc4a0b8c4a27"

        def install
          bin.install "datumctl"
        end
      end
    end
  end
end
