# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datumctl < Formula
  desc "A network cloud, built on open source."
  homepage "https://www.datum.net/"
  version "0.11.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.11.0/datumctl_Darwin_x86_64.tar.gz"
      sha256 "90169ef01bb307ddcb838f187d564996ac9c3d98cc42952d98c326759f9cfd0e"

      define_method(:install) do
        bin.install "datumctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.11.0/datumctl_Darwin_arm64.tar.gz"
      sha256 "4ae77358be248a1629db58b1f360de7c5b90ac3ef43a9017a6a846ad46225a1d"

      define_method(:install) do
        bin.install "datumctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.11.0/datumctl_Linux_x86_64.tar.gz"
      sha256 "4c28100bbac1eb7fda1ad9d43d85035c0f7fb9571bcb433a31ef99489321f94a"
      define_method(:install) do
        bin.install "datumctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datum-cloud/datumctl/releases/download/v0.11.0/datumctl_Linux_arm64.tar.gz"
      sha256 "bc6fa8acb8c34d835f1eca5ed70ea3aac76a3ec56a3b635765661fda08bba22b"
      define_method(:install) do
        bin.install "datumctl"
      end
    end
  end
end
